// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

import (
	"context"
	"github.com/jqs7/zwei/biz"
	"github.com/jqs7/zwei/db"
	"github.com/jqs7/zwei/env"
	"sync"
)

// Injectors from wire.go:

func Run(ctx context.Context, cancel context.CancelFunc) *sync.WaitGroup {
	specification := env.Init()
	pgDB := db.Instance(specification)
	handler := biz.NewHandler(pgDB, specification)
	bot := ProvideBot(specification, handler)
	waitGroup := Runner(ctx, cancel, pgDB, bot)
	return waitGroup
}
